commit_template = '''ci: {operation} files from {template}

bringing common files in template up to date
template: {template}
branch: {branch}
commit: {commit}

this commit was generated by [templatron](https://github.com/charlesthomas/templatron)'''
