name: Build and Publish Image

on:
  workflow_run:
    workflows: ["Semantic Release"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: registry auth
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract version
        run: |
          echo "VERSION=$(grep __version__ templatron/__init__.py | cut -f 2 -d = | tr -d ' ' | tr -d \")" >> "$GITHUB_ENV" 

      - name: image metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          flavor: |
            latest=true
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,enable=true,value=${{ env.VERSION }}

      - name: build & push image
        uses: docker/build-push-action@831ca179d3cf91cf0c90ca465a408fa61e2129a2
        with:
          build-args: UPSTREAM_VERSION=${{ env.UPSTREAM_VERSION }}
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
